---
- name: allow packet forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    sysctl_file: /etc/sysctl.d/99-router.conf

- name: setup gobgpd
  include_tasks: gobgpd.yml

- name: setup zebra
  include_tasks: zebra.yml
