[global.config]
  as = 64512
  router-id = "172.17.1.1"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "172.17.0.21"
    peer-as = 64522

[[neighbors]]
  [neighbors.config]
    neighbor-address = "172.17.0.22"
    peer-as = 64522

[[neighbors]]
  [neighbors.config]
    neighbor-address = "172.17.0.23"
    peer-as = 64522
