[zebra]
  [zebra.config]
    enabled = true
    url = "unix:/var/run/quagga/zserv.api"
    redistribute-route-type-list = ["connect"]
    version = 2

[global.config]
  as = 64512
  router-id = "172.17.1.1"

[global.use-multiple-paths.config]
  enabled = true

[[neighbors]]
  [neighbors.config]
    neighbor-address = "172.17.0.21"
    peer-as = 64522
  [neighbors.timers.config]
    connect-retry = 5
    keepalive-interval = 3

[[neighbors]]
  [neighbors.config]
    neighbor-address = "172.17.0.22"
    peer-as = 64522
  [neighbors.timers.config]
    connect-retry = 5
    keepalive-interval = 3

[[neighbors]]
  [neighbors.config]
    neighbor-address = "172.17.0.23"
    peer-as = 64522
  [neighbors.timers.config]
    connect-retry = 5
    keepalive-interval = 3
