[zebra]
  [zebra.config]
    enabled = true
    url = "unix:/var/run/quagga/zserv.api"
    redistribute-route-type-list = ["connect"]
    version = 2

[global.config]
  as = 64512
  router-id = "172.17.1.1"

[global.use-multiple-paths.config]
  enabled = true

[[neighbors]]
  [neighbors.config]
    neighbor-address = "172.17.0.21"
    peer-as = 64522
  [neighbors.timers.config]
    connect-retry = 5
    keepalive-interval = 3

[[neighbors]]
  [neighbors.config]
    neighbor-address = "172.17.0.22"
    peer-as = 64522
  [neighbors.timers.config]
    connect-retry = 5
    keepalive-interval = 3

[[neighbors]]
  [neighbors.config]
    neighbor-address = "172.17.0.23"
    peer-as = 64522
  [neighbors.timers.config]
    connect-retry = 5
    keepalive-interval = 3

[[defined-sets.prefix-sets]]
  prefix-set-name = "ignore-prefix"
  [[defined-sets.prefix-sets.prefix-list]]
    ip-prefix = "10.0.2.0/24"

[[policy-definitions]]
  name = "reject-policy"
  [[policy-definitions.statements]]
    [policy-definitions.statements.conditions.match-prefix-set]
      prefix-set = "ignore-prefix"
    [policy-definitions.statements.actions]
      route-disposition = "reject-route"

[global.apply-policy.config]
  import-policy-list = ["reject-policy"]
  default-import-policy = "accept-route"
