---
- name: install packages
  apt:
    name: ['curl']
    state: present
    update_cache: yes
    install_recommends: no
    force_apt_get: yes

- name: add static-route file
  copy:
    src: ../files/99-static-route.yaml
    dest: /etc/netplan/99-static-route.yaml
    mode: 0644
    owner: root
    group: root
  register: add_static_route

- name: netplan apply
  command: netplan apply
  when: add_static_route is changed
