---
- name: install packages
  apt:
    name: ['curl', 'httping']
    state: present
    update_cache: yes
    install_recommends: no
    force_apt_get: yes

- name: add static-route file
  copy:
    src: ../files/99-static-route.yaml
    dest: /etc/netplan/99-static-route.yaml
    mode: 0644
    owner: root
    group: root
  register: update_static_route_for_k8s_cluster_network

- name: netplan apply
  command: netplan apply
  when: update_static_route_for_k8s_cluster_network is changed
